/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Advanceddate: typeof import('./src/components/input/date/advanceddate.vue')['default']
    Avatar: typeof import('./src/components/avatar/avatar.vue')['default']
    Badge: typeof import('./src/components/badge/badge.vue')['default']
    Button: typeof import('./src/components/button/button.vue')['default']
    Chart: typeof import('./src/components/charts/chart.vue')['default']
    Checkbox: typeof import('./src/components/checkbox/checkbox.vue')['default']
    Confirm: typeof import('./src/components/button/confirm/confirm.vue')['default']
    Dateinput: typeof import('./src/components/input/date/dateinput.vue')['default']
    Divider: typeof import('./src/components/divider/divider.vue')['default']
    Dropdown: typeof import('./src/components/button/dropdown/dropdown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElInput: typeof import('element-plus/es')['ElInput']
    Icon: typeof import('./src/components/icon/icon.vue')['default']
    Input: typeof import('./src/components/input/input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/skeleton/skeleton.vue')['default']
    Treeview: typeof import('./src/components/treeview/treeview.vue')['default']
  }
}
